trigger:
- main

variables:
  # Container registry variables
  ACR_NAME: 'vernievotazure'
  ACR_LOGIN_SERVER: 'vernievotazure.azurecr.io'
  IMAGE_NAME: 'tempconverter'
  IMAGE_TAG: 'latest'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: Docker@2
      inputs:
        containerRegistry: '$(ACR_NAME)'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(IMAGE_TAG)
