version: '3.7'

services:
  db:
    image:  mysql:8.0
    environment:
      MYSQL_DATABASE: tempconverter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - "3306:3306"

  app:
    image: github.com/bmustac/tempconverter
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASS: password
      DB_HOST: db
      DB_NAME: tempconverter
      ports:
      - "80:5000"
      deploy:
        replicas: 3


